export const suggestions =[
    { id: 1, label: "JavaScript" },
    { id: 2, label: "Python" },
    { id: 3, label: "Java" },
    { id: 4, label: "C++" },
    { id: 5, label: "Ruby" },
    { id: 6, label: "Swift" },
    { id: 7, label: "Go" },
    { id: 8, label: "PHP" },
    { id: 9, label: "Kotlin" },
    { id: 10, label: "Rust" },
    { id: 11, label: "TypeScript" },
    { id: 12, label: "Scala" },
    { id: 13, label: "C#" },
    { id: 14, label: "Objective-C" },
    { id: 15, label: "Perl" },
    { id: 16, label: "Haskell" },
    { id: 17, label: "Lua" },
    { id: 18, label: "Dart" },
    { id: 19, label: "Elixir" },
    { id: 20, label: "F#" },
    { id: 21, label: "Clojure" },
    { id: 22, label: "Groovy" },
    { id: 23, label: "Julia" },
    { id: 24, label: "Matlab" },
    { id: 25, label: "Objective-C++" },
    { id: 26, label: "R" },
    { id: 27, label: "Shell" },
    { id: 28, label: "VB.NET" },
    { id: 29, label: "Visual Basic" },
    { id: 30, label: "Assembly" },
    { id: 31, label: "Time management" },
    { id: 32, label: "Communication" },
    { id: 33, label: "Problem solving" },
    { id: 34, label: "Critical thinking" },
    { id: 35, label: "Leadership" },
    { id: 36, label: "Adaptability" },
    { id: 37, label: "Teamwork" },
    { id: 38, label: "Decision making" },
    { id: 39, label: "Creativity" },
    { id: 40, label: "Emotional intelligence" },
    { id: 41, label: "Stress management" },
    { id: 42, label: "Negotiation" },
    { id: 43, label: "Self-motivation" },
    { id: 44, label: "Patience" },
    { id: 45, label: "Conflict resolution" },
    { id: 46, label: "Networking" },
    { id: 47, label: "Decision-making" },
    { id: 48, label: "Interpersonal skills" },
    { id: 49, label: "Public speaking" },
    { id: 50, label: "Time management" },
    { id: 51, label: "Financial management" },
    
];


  
  